name: "Forced - Merge pr to staging"
run-name: "Forced - Merging #${{ github.event.issue.number }} to staging"

on:
  issue_comment:
    types: [created]

jobs:
  forced-merge-to-staging:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/forceDeployStaging')}}
    runs-on: [ubuntu-latest]
    outputs:
      reviews: ${{ steps.reviews.outputs.state }}
    steps:
      - id: reviews
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pr: ${{ github.event.issue.number }}
        run: |
          state=$(gh pr view "$pr" \
              --repo "edpei/skills-hello-github-actions-pub" \
              --json reviewDecision \
              --jq '.reviewDecision')
          echo "NENENENE $state $pr -- $GITHUB_OUTPUT aaa ${{ github.event.issue.number }} - bbb ${{ github.event.number }}"
          echo "state=$state" >> "$GITHUB_OUTPUT"
  runTests:
    runs-on: [ubuntu-latest]
    needs: forced-merge-to-staging
    steps:
      - id: echos
        run: |
          echo "Running tests"
          echo "NENENENE ${{ needs.forced-merge-to-staging.event.reviews }}"
