name: "Forced - Merge pr to staging"
run-name: "Forced - Merging #${{ github.event.issue.number }} to staging"

on:
  issue_comment:
    types: [created]

jobs:
  forced-merge-to-staging:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.html_url, '/forceDeployStaging')}}
    runs-on: [self-hosted]
    outputs:
      reviews: ${{ steps.reviews.outputs.state }}
    steps:
      - id: reviews
        env:
          pr: ${{ github.event.issue.number }}
        run: |
          state=$(gh pr view "$pr" \
              --repo "Launchmetrics/GIS-mekong"
              --json reviewDecision \
              --jq '.reviewDecision')
          state2=$(gh pr view "$pr" \
              --repo "GIS-mekong"
              --json reviewDecision \
              --jq '.reviewDecision')
          echo "state=$state" >> "$GITHUB_OUTPUT"
          echo "state2=$state2" >> "$GITHUB_OUTPUT"
          echo "NENENENE $state $state2 ${{ github.event.issue.number }} ${{ github.event.number }}"
