name: "Forced - Merge pr to staging"
run-name: "Forced - Merging #${{ github.event.issue.number }} to staging"

on:
  issue_comment:
    types: [created]

jobs:
  forced-merge-to-staging:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/forceDeployStaging')}}
    runs-on: [ubuntu-latest]
    outputs:
      reviews: ${{ steps.reviews.outputs.state }}
    steps:
      - id: reviews
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pr: ${{ github.event.issue.number }}
        run: |
          state=$(gh pr view "$pr" \
              --repo "skills-hello-github-actions-pub "
              --json reviewDecision \
              --jq '.reviewDecision')
          echo "state=$state" >> "$GITHUB_OUTPUT"
          echo "NENENENE $state ${{ github.event.issue.number }} ${{ github.event.number }}"
